### ISSUE TITLE
Start sync: don't wait for schedule

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#1036]
We've recently introduced the feature to [pause and resume syncs](https://docs.nango.dev/api-reference/sync/start).

This feature proves handy when setting metadata for a sync:

1. Initiate OAuth (with `auto_start: false`)
2. Input metadata
3. Begin the sync

However, a challenge arises in this flow. Even if these three steps are executed quickly, the sync, once started, must wait until the next scheduled run to begin syncing the initial data. This means we inadvertently create the maximum possible delay before the data starts syncing, based on the sync frequency specified by the developer.

To address this, we should adjust the schedule to start counting from the moment the sync is initiated.

**Comment by khaliqgant** [comment]
@bastienbeurier #1055 updates the logic so that on a sync start (called enum UNPAUSE in code):

1. The schedule is unpaused via the temporal sdk
2. The sync is immediately triggered to run
3. The schedule offset is updated so that the schedule runs according to the moment it was unpaused which satisfies your comment "we should adjust the schedule to start counting from the moment the sync is initiated."

This replaces previous behavior where:
1. Schedule is unpaused via the temporal SDK

This left us with no immediate schedule trigger and the previous schedule coming into effect with the original offset intact so it would pick up where it originally would have been schedule to run. Explained by an example:

I create a sync at 1335 with a runs property of "every 30 minuutes". That means the next sync run will be at 1405. I pause the sync at 1337. I unpause the sync at 1340. The sync won't run until 1405 still.

With the updated implementation the sync will run right when I unpause it and then will run with an updated schedule next at 1410.
