### ISSUE TITLE
SDK: The authorization window was closed before the authorization flow was completed

### ISSUE THREAD

**Issue by ciza99** [NangoHQ/nango#1251]
Iam getting `The authorization window was closed before the authorization flow was completed` error with the frontend SDK. The error is thrown when I go through the whole oauth process successfully.

Iam using the SDK from https://www.jsdelivr.com/package/npm/@nangohq/frontend with version **0.36.8**.
The weird thing is, if I go through the oatuh popup modal quickly, the oauth finishes successfully without any error.

I also get `Cross-Origin-Opener-Policy policy would block the window.window call.` errors in the console, but I am not sure if that is relevant because everything seems to work otherwise and the modal window does appear.

When I checked the code it seems to me that [this condition inside the interval](https://github.com/NangoHQ/nango/blob/0c50a09e6c69285a93de691ead429c2f4b54f925/packages/frontend/lib/index.ts#L137C10-L137C10) gets triggered before the promise is resolved from the modal. But I dont see what or when closes the modal.

Edit: I forgot to mention that this is happening with youtube integration, I have not tested other integrations yet.

**Comment by kenkantzer-truss** [comment]
The google API approval team just hit this issue too, we're on 0.35.4 for front end. This is the screenshot they forwarded to me yesterday:

![image](https://github.com/NangoHQ/nango/assets/118487850/a9af3314-ee09-481e-bbfc-ff1681750e17)

**Comment by kenkantzer-truss** [comment]
Tried to reproduce this for a while: 

1. I could not repro this, so if anything, it's either a race condition as mentioned above or possibly a timeout somewhere.
2. I've noticed this, the Google Oauth endpoints in particular take FOREVER the first time (often 10-15 seconds), and then seem to cache it, and are nearly instantaneous when I re-try.
3. I did notice that Heroku gave an H15 error that correlates with the error message.
<img width="1173" alt="Screenshot 2023-11-15 at 7 51 33 PM" src="https://github.com/NangoHQ/nango/assets/118487850/ae53cb6f-21cf-4e6e-9aef-22dbeb8c3218">

Apparently though, [keepAlives are needed to avoid 15 timeouts](https://lxcid.com/2017/06/03/socket.io-heroku), maybe?

I wonder if we need to add a keepalive / ping here: https://github.com/NangoHQ/nango/blob/cb1275db7ca9d94fab3725c908f2628159f41124/packages/server/lib/server.ts#L201

**Comment by ciza99** [comment]
Good to know I am not the only one, I also forgot to mention that the connection gets created even when the error is thrown. So the whole process goes through.

The keepalive / ping could maybe explain why it works if I go through the oatuh quickly?
Could I ask what closes the modal window on success? I dont see it anywhere in the SDK.

**Comment by khaliqgant** [comment]
Thanks both and sorry for the troubles here.

Few questions:
1. Are you both self hosting Nango?
2. Can you reliably reproduce this? Sounds like one of you couldn't?
3. Can you send a video of this happening?

> Could I ask what closes the modal window on success? I dont see it anywhere in the SDK.

The modal closure stems from a server side call that is sent via the websocket. So to trace it fully:
1. OAuth callback gets called when the oauth connection goes through and sends a notifySuccess https://github.com/NangoHQ/nango/blob/master/packages/server/lib/controllers/oauth.controller.ts#L862
2. The websocket client does some cleanup and then sends an html message: https://github.com/NangoHQ/nango/blob/master/packages/server/lib/clients/web-socket.client.ts#L70
3. The success message includes a javascript snippet that closes the modal https://github.com/NangoHQ/nango/blob/master/packages/server/lib/utils/utils.ts#L216

😅

I spent some time with this and tried a few different things but could not reproduce this at all. The best fix I could come up with based on what information you provided was to add a delay in triggering the error that the modal was closed early since you said it might be a race condition. That update is in https://github.com/NangoHQ/nango/commit/4524223eb36fe35c35f041e2872d7d2c03c5794d

I'll wait on merging this until I get some more information.

Thanks!

**Comment by kenkantzer-truss** [comment]
@khaliqgant, no worries at all, you guys are doing awesome! So, the error did not reappear, and when I tested it, it is definitely not "every time". I even tried with slow bandwidth throttling to see if it appears when things are slower.

Honestly, I would suspect the following:
1. It may only be reproducable on self-hosted Heroku, where Heroku times things out relatively aggressively
2. This only affects Google integrations, because their oauth takes FOREVER the first time (15+ seconds sometimes)
3. The error has something to do with heroku timing out some request for long oauth request responses.

Sorry, I know there's no smoking gun here, so feel free to close (tho, if it affects Google integrations at large, it might be worth looking into / accounting for!)

**Comment by wub** [comment]
We're experiencing this issue as well (Google only). The Google oauth loads within a second or two for us, and happens for me both locally and in staging. It doesn't seem to be tied to a timeout issue for us.

* This issue does **not** occur in `@nangohq/frontend v0.33.0`
* This issue **does** occur in `@nangohq/frontend v0.35.5`

In v0.35.5 and up, when we open the Google modal we get the same error:
> Cross-Origin-Opener-Policy policy would block the window.window call.

And then, upon successfully completing the flow, we receive the "window was closed" error as above. We're on Nango cloud.

@khaliqgant I can give you a repro scenario + video on our staging site via Nango Slack if you'd like.

**Comment by kenkantzer-truss** [comment]
If it helps, we are on v0.35.4 and this is happening, which lines up.

**Comment by khaliqgant** [comment]
Thanks both! Can you see if an update from @TBonnin in https://github.com/NangoHQ/nango/pull/1299 fixes the issue? The frontend SDK version is [0.36.31](https://www.npmjs.com/package/@nangohq/frontend/v/0.36.31)

**Comment by wub** [comment]
Thanks @TBonnin and @khaliqgant - that works perfectly!

We still get the `Cross-Origin-Opener-Policy policy would block the window.window call` log, but that doesn't cause any issues.

**Comment by bastienbeurier** [comment]
This has been resolved by @TBonnin
