### ISSUE TITLE
Python backend SDK

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#316]
For projects using Python in the backend it would be great to have a Python SDK.

**Comment by 0xRaduan** [comment]
asked about this in the slack recently, @bastienbeurier created next placeholder repo: https://github.com/NangoHQ/nango-python. 

I might get to it, but not the biggest priority on my list, since we are currently integrating only with one service and pretty straightforward. 

But have put it to my backlog for now.

**Comment by ha-sante** [comment]
Not anymore @0xRaduan :) - I haven't gotten to that part yet, but will try* (I am yet to know what I am up against in full) to build the python sdk in full with buildwithfern.com

I dont even know what I am dealing with at this point but just leaving this here to commit.

- I know I need an OpenAPI spec somewhere and know you might have it somewhere for your mintlify instance.
