### ISSUE TITLE
Refreshing the Connection creation page shows an error

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#386]
<img width="1512" alt="Screenshot 2023-03-21 at 09 14 02" src="https://user-images.githubusercontent.com/2560456/226671322-86cbcab5-fd64-4744-9b50-51d5cff21223.png">

**Comment by uncle-tee** [comment]
Please can give more details on this issue?

**Comment by bastienbeurier** [comment]
Of course! 

If you go to the "Connections" tab, click "Add New", you get to the `/connection/create` page. Refreshing this page triggers this error.

**Comment by Chandu** [comment]
The root cause is the conflict of the routes (`/connection/*`) on both server side and the client side (UI routes).

Possible options (#1, #2 are breaking changes and #3 would be a breaking change if there are any other clients/scripts that doesn't pass the proper content-type header for JSON content):

1. Modify the server side route path for connection from `/connection/*` to something that doesn't conflict with the UI route 
2. Modify the route path on the client side 
3. Check the content-type header on the server side and if it happens to be for a JSON content, then pass it on to connection controller, else let the `*` route handle the request which would subsequently be handled by the UI router.

![image](https://user-images.githubusercontent.com/261027/230143064-15e621df-b8d8-4126-baec-5ff1624b2eaa.png)

**Comment by bastienbeurier** [comment]
Thanks a lot for investigating @Chandu Would you mind pushing a fix for this?

**Comment by Chandu** [comment]
Sure @bastienbeurier. However a fix based on any of the three optikns might introduce a breaking change.

**Comment by bastienbeurier** [comment]
Ok, but I don't understand how these routes can conflict when all server routes are prefixed with `/api/v1` and not client side ones?

**Comment by Chandu** [comment]
@bastienbeurier There are few routes without api prefix, e.g https://github.com/NangoHQ/nango/blob/master/packages/server/lib/server.ts#L63

**Comment by bastienbeurier** [comment]
Oh sorry you are right! 

The best way would be to change the web app routes to avoid an SDK breaking change then.

This would indeed break this page's UI for self-hosted instances, but they can easily upgrade their Docker container to fix it!

 Let me know if you want to do it or I should jump on it.

**Comment by Chandu** [comment]
I will take care of it @bastienbeurier
