### ISSUE TITLE
Pinterest

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#403]

**Comment by uncle-tee** [comment]
This is ongoing by @uncle-tee.

**Comment by uncle-tee** [comment]
Pin interest requires that a business account is created, however, this goes through approval. I will like you to create this, since it involves submitting company information.

Here is a link to create an account on Pinterest [here](https://developers.pinterest.com/account-setup/).
If you need a reference to setting up an app you can find it [here](https://developers.pinterest.com/docs/getting-started/set-up-app/#Register%20and%20get%20your%20app%20ID%20and%20secret%20key)

**Comment by rguldener** [comment]
Thanks for researching this @uncle-tee!
I think we can get back to this later, closing it for now.
