### ISSUE TITLE
WeChat

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#416]

**Comment by uncle-tee** [comment]
This is a little bit complex and will require some code tweaking and ground research. wechat uses the same OAuth process, however, it is called appId instead of client_id, it also uses secret instead of secret. Here is the documentation [here](https://developers.weixin.qq.com/doc/oplatform/en/Website_App/WeChat_Login/Wechat_Login.html) and [here](https://developers.weixin.qq.com/doc/offiaccount/en/OA_Web_Apps/Wechat_webpage_authorization.html)

**Comment by bastienbeurier** [comment]
Understood, thank you for researching. I'll mark as blocked for now.

**Comment by rguldener** [comment]
Closing this for now until we have a request from a customer for it.
