### ISSUE TITLE
Handle APIs that reject refreshes of still-valid tokens

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#748]
From this [thread](https://nango-community.slack.com/archives/C04ABR352H0/p1688637156163949) on the community.

The [Exact API](https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-oauth-eol-oauth-devstep3) issues tokens valid for 10mins and returns a 4xx when refreshing a still-valid token. 

Nango refreshes tokens that are expiring in <15mins, as a security margin. 

So Nango tries to refresh Exact tokens each times and fails. 

Potential solutions could be: 
1. Lower security margin for all APIs to something like 1mins
2. Have a flag in `providers.yaml` to remove/lower the security margin for specific providers

In any case, I don't think we should remove the security margin entirely, to avoid race conditions when the user fetches a token that's about to expire.

**Comment by rguldener** [comment]
I think in this case option 2 is better, if we implement it so that the time buffer is optionally configurable (e.g. number of minutes) in the `providers.yaml`.

A 1min timeout is very tight IMO if you take into account that there can be clock shifts/differences and some users may cache the access token for several API requests (yes they should not, but reality is many do I think).

Additionally I think we should adhere to the design principle that we should not deteriorate quality of service for all APIs just because of one (or a few) badly designed APIs.

The "right" value is also unlikely to be globally applicable, so optional config per API makes sense from my perspective.

**Comment by bramkn** [comment]
Setting an optional provider parameter sounds like the best idea indeed.
1 minute is also not enough for this specific one though. I know it is pretty sh*t but there is of course nothing we can do about it.
To be fair, for my personal usecase it is fine for most instances. As most often you request the access token and then make the api request to retrieve the data/ push data.

As long as the user knows this is what is happening you can work around it.
