### ISSUE TITLE
Is this secure?

### ISSUE THREAD

**Issue by joshsny** [NangoHQ/nango#759]
I have been implementing Nango into a test project and I am loving it so far!

I had issues when implementing a login flow securely, which I am guessing is due to me doing it wrong.

I get a user to login with `nango.auth('github', '<user-id>');` and the next suggested step is to use this id server-side to make calls

```
nango.getRecords({
    providerConfigKey: 'github',
    connectionId: '<user-id>',
    model: 'GithubIssues', // Or anything else you want to sync
});
```

The problem here is that the `connectionId` is specified client-side, so I cannot trust it as a user with ID 1 could easily initiate a flow for `nango.auth('github', '2')`.

How can I get around the `connectionId` being untrusted? I'd have ideally liked to specify the `connectionId` server-side and passed a JWT or something similar to the client.

**Comment by bastienbeurier** [comment]
Hi @joshsny! This is a legitimate concern and has been addressed with the (currently undocumented) HMAC feature from #591 (task to reintroduce the docs for the feature: #726)

This feature was initially implemented for OSS. It is currently being ported to Cloud and should be released tomorrow. 

Here are some instructions to use HMAC (⚠️ with the new release, the HMAC settings will be in the dashboard, not env variables).

### Restricting the creation of new connections

By default, your front-end application can attempt to create a new connection using any provider config key and connection ID.

In some applications, you may wish to restrict this, for example:

-   You may want to restrict the ability to create connections for a given provider config key based on the current user, if some users are permitted to create connections to that provider and others are not.
-   You may want to use your applications user ID as the connection ID, and need to ensure that application user is the only one that can create a new connection with that connection ID.

Nango provides the ability for an application to restrict the creation of new connections by the use of HMAC digests. The HMAC feature is disabled by default.

Once the HMAC feature is enabled, the Nango server will require that a HMAC digest is provided for every attempt to create a new connection from your front-end application.

The HMAC digest is generated by your application using a specified algorithm and key, and the digest is over the combination of the provider config key and the connection ID.

The algorithm and key must be shared between your application and the Nango server, so that the Nango server can verify the HMAC digest is correct. If the Nango server determines that the HMAC digest is missing or is invalid, then the request to create the new connection will be rejected.

Your application should only generate the HMAC digest after performing all authentication and authorization checks to ensure that the request to create the new connection is permitted. Your application should also keep the specified key private, and not reveal it to your front-end application or your end-users.

To enable the HMAC feature on the Nango server, set the following environment variables and restart the server:

```bash
NANGO_HMAC_ENABLED=true
NANGO_HMAC_KEY=<PICK-A-KEY>
```

Optionally, you change the algorithm from the default of `sha256` by setting the following environment variable and restarting the server:

```bash
NANGO_HMAC_ALGORITHM=sha384
```

When the HMAC feature is enabled, your front-end applicaton must always pass in an HMAC digest as follows:

```js
nango.auth('<CONFIG-KEY>', '<CONNECTION-ID>', { hmac: '<HMAC-DIGEST>' });
```

The HMAC digest can be generated by using the following code in your back-end application:

```js
import * as crypto from 'node:crypto';

// TODO: execute authentication and authorization checks before generating the HMAC digest.

// The default value for '<HMAC-ALGORITHM>' is 'sha256'.
// The value of '<HMAC-KEY>' should match the HMAC key passed to the Nango server.
const hmac = crypto.createHmac('<HMAC-ALGORITHM>', '<HMAC-KEY>');
hmac.update('<CONFIG-KEY>:<CONNECTION-ID>');
const digest = hmac.digest('hex');

// TODO: return the value of `digest` to the front-end application to pass to `nango.auth`.
```

**Comment by bastienbeurier** [comment]
Closing this one and linking the new official docs about HMAC: https://docs.nango.dev/guides/oauth#securing-the-frontend-sdk-calls-with-hmac
