### ISSUE TITLE
Frontend popup to let end users input API Key

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#808]
Currently `nango.auth` triggers a popup for OAuth, but asks for credentials in the params for API Key & Basic auth. I think we should align the two and implement a popup for API Key & Basic as well (with text field(s) to input the credentials).

For API Key & Basic key, the popup should also contain some basic instructions (1-liner?) to find the API Key for the specific API. These instructions could also be entries in `providers.yaml`.

**Comment by Bhardwaj-Himanshu** [comment]
Hi @bastienbeurier , as being new to the community and looking forward to contributing it! I understood a very little of what's being the issue here, but in my understanding are you recommending to add `new entry fields when clicked for O-auth` under the credentials section?
Something like-
![Selection_004](https://github.com/NangoHQ/nango/assets/74407676/f7ce3040-2fb8-4541-b49f-a1424025c513)
So that the O-auth does not ask for the keys again?

Let me know if I am proceeding in a wrong direction here, and if you could provide some reference images about the issue to understand it better?
Thanks

**Comment by bastienbeurier** [comment]
Hi @Bhardwaj-Himanshu, the idea behind this issue was a little different. It is about having a similar popup experience for API key than for OAuth, similarly to this screenshot: 
<img width="1507" alt="Screenshot 2023-07-27 at 09 11 30" src="https://github.com/NangoHQ/nango/assets/2560456/2a552b79-c772-4ce0-9cf5-d42056a297bf">


Today, the encouraged way to contribute is to add APIs with the [contribute guide](https://docs.nango.dev/contribute). Unfortunately, we currently don't have much bandwidth to provide detailed guidance about other contributions, unless the contribution is fixing an immediate customer problem.

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
