### ISSUE TITLE
Use of "Open Source" in advertising and marketing

### ISSUE THREAD

**Issue by ssddanbrown** [NangoHQ/nango#900]
Hello,

I just wanted to query your use of "open source" in your advertising and marketing, as can be seen in multiple locations including [this repo](https://github.com/NangoHQ/nango/blob/fba71a355a537a85d48b70cef9fed8d6e98a1b71/README.md?plain=1#L11), [your website](https://www.nango.dev/) (Where "100% Open Source" is used) and [external marketing posts](https://www.reddit.com/r/opensource/comments/10rts84/opensource_service_to_easily_get_store_refresh/).

I'm querying this due to [the license used](https://github.com/NangoHQ/nango/blob/master/LICENSE) (ELv2) is not generally regarded as open source by many since it does not meet the requirements of the [open source definition](https://opensource.org/osd/) which is what open source has been built and popularised upon.

I'm not saying that use of the ELv2 itself is an issue, I totally respect your right to choose your own license and to protect your efforts, this is specifically regarding advertising this under as "open source" which I feel could be misleading to many while impacting the term for those that do take the risks to provide their work under in a way that does meet the common open source definition. I've written more about [why I think the term is important here](https://danb.me/blog/why-open-source-term-is-important/).

- Are you aware you're using "open source" in a way that many would consider misleading?
- If so, is there a specific definition you do follow for open source?

PS. If this is better suited to a GH discussion instead of an issue, feel free to migrate it, but it didn't look like discussions were too commonly used in this repo.

**Comment by evereq** [comment]
I was like WOW, I finally found open-source software for Unified APIs / embedded iPaaS etc, before I saw that the license is Elastic 2.0 😢 . 

Before Nango, I found crazy large list of very expensive software with similar features (maybe someone will find useful) listed below:

- https://hotglue.com/
- https://www.apideck.com/
- https://merge.dev/
- https://www.vessel.dev/
- https://www.pandium.com/
- https://www.codat.io/
- https://unified.to/
- https://cyclr.com/
- https://www.useparagon.com/
- https://tray.io/products/embedded
- https://morphed.io/
- https://www.kombo.dev/
- https://www.tryfinch.com/
- https://www.cdata.com/
- https://appdirect.com/

All of the above commercial software, and of course not open-source and cost $$$.
To my surprise, however, the pricing of Nango also starts from 250$+ per month - https://www.nango.dev/pricing (The free version is very limited for most real-life scenarios I think)

So I wonder how anyone can use this kind of software for integrations with other software if it's ELv2 licensed?
As I see it, most of the projects that need to integrate with other software will be probably some sort of SaaS that provides services to customers so it can't really use Nango's "open-source" license ("open-source" because it's not really Open-Source haha) in my understanding? I would assume that AGPLv3 will be possibly better license for those, but even that will be too restrictive in some cases...

Still, if the founders of Nango reading this or someone who knows more about Elastic license, my question is: what if we ask all our SaaS "customers" to install Nango self-hosted for themselves and from our SaaS platform we will just allow them to specify API endpoint for Nango (So, Nango is hosted by each customer separately for own usage, not by us). Will it be still a violation of the Elastic 2.0 license?

Of course, we can fork 1-year-old version of Nango before they switched licenses (i.e. right before https://github.com/NangoHQ/nango/commit/e0734f12ce31dcd7e5852b6119b5a7dc792279a1) and try to make it work somehow... But I would really love to get some details from the Nango team about what they can offer for SaaS platforms in general and specifically for our platform http://github.com/ever-co/ever-gauzy.

**Comment by bastienbeurier** [comment]
Thank you for raising these interesting points.

I think this [page](https://www.elastic.co/licensing/elastic-license/faq) from Elastic clarifies these questions.

In particular, it outlines the specific cases when ELv2 it's restrictive vs. not. Taking Elasticsearch as an example: 

> I'm using Elasticsearch to put a search box on my cat-picture SaaS product.
> This is permitted under ELv2. Meow!
> 
> I'm a contractor setting up Elasticsearch and Kibana for my clients to use internally.
> This is permitted under ELv2, because you are not providing the software as a managed service.
> 
> My cat-picture SaaS product shows view-only Kibana dashboards of analytics on searches and views.
> This is permitted under ELv2. The use of Kibana in this case is limited and this does not represent access to a substantial portion of the functionality of Kibana.
> 
> I am a Managed Service Provider (MSP) running Elasticsearch and Kibana for my customers.
> If your customers do not access Elasticsearch and Kibana, this is permitted under ELv2. If your customers do have access to substantial portions of the functionality of either Elasticsearch and Kibana as part of your service, this may not be permitted.
> 
> I provide Elasticsearch and Kibana as a service, where my customers have direct access to substantial portions of the Elasticsearch APIs and Kibana UI.
> This use is not permitted under the ELv2. Please reach out to us to discuss your options.

In short, for Nango, you can always use Nango in your SaaS to create any integration you want, but you can't offer Nango-as-a-service (e.g. offering the Nango dashboard, CLI, developer tooling, to your customers). 

The main limitation of this license is to prevent copy cats, while allowing all other forms of usage. Our opinion is that preventing copy cats is fair and the resulting software is undoubtedly more on the side of open-source than close-source.

**Comment by evereq** [comment]
Thank you for getting back @bastienbeurier, I'm also 💯  for preventing copycats - it's bad for everyone!

It's very hard to define what it means for usage of a project like Nango when we say "Your customers don't have access to substantial portions of the functionality... (of Nango)". We may not provide customers access to the Dashboard of Nango, to CLI, to developer tooling, but we will definitely need to provide access to the API of Nango to make such integrations with third-party APIs work via Nango, right? That's exactly a devil in the details of ELv2 as I understand it (if I understand it correctly of course). 
We will not "host" Nango to compete with Nango, but we will host it to allow usage by our customers via API I am still not sure if it's allowed by ELv2 or not, but feels like it's really problematic...

So unless you will explicitly give us such permission to integrate on API level with our "self-hosted" version of Nango, I am afraid it's a problem for us to use it. 

In addition as @ssddanbrown points out, I think it's also a bit problematic to call the current release as true "Open-Source". You can call it just "Open", that's how people do it in such cases, but calling it "Open-Source" can really make some people violate your license because of misunderstanding. 

I do understand a LOT of effort you guys put into this amazing project, but think above issues are important to clarify and resolve :)

**Comment by ssddanbrown** [comment]
> You can call it just "Open", that's how people do it in such cases, 

"Fair code" and "source available" are both often used with these kinds of licenses. I've always thought "fair code" could become a powerful term if picked up. Using "open" may still be considered "openwashing" by some, although in my view it's still better than using "open source" which is specifically a term popularized upon a definition which does not apply here.

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker

**Comment by kerimcharfi** [comment]
Is there any clarification on the licensing boundaries? Its too vage and risky for us to integrate a self hosted nango into our SaaS.
We would like to use it for our workflow engine, wont expose any nango tooling, dashboards or client sdk

**Comment by bastienbeurier** [comment]
> Is there any clarification on the licensing boundaries? Its too vage and risky for us to integrate a self hosted nango into our SaaS. We would like to use it for our workflow engine, wont expose any nango tooling, dashboards or client sdk

Hi @kerimcharfi, feel free to reach out to discuss this: https://calendly.com/d/cryk-hhd-y79
