### ISSUE TITLE
Exiting out of an OAuth window does not result in error

### ISSUE THREAD

**Issue by MoSheikh** [NangoHQ/nango#917]
Currently, an end user is able to execute an OAuth flow and cancel part way by exiting out of the OAuth window. However, this does not result in an error, but a pending promise that is not resolved. 

I believe that the proper behaviour here would be to throw an error and execute the error handler if the window is closed and the success handler has not been executed.

**Comment by rguldener** [comment]
Hi @MoSheikh 

This is a known limitation currently and tracked in #571 .
Due to browser security we literally don't know what happens with the popup window once we made the redirect to the OAuth provider, so we also cannot detect when the user closes it.

If you have an idea on how to improve or fix this feel free to add to the other issue :)
Closing this here as a duplicate.
