### ISSUE TITLE
Refresh instructions & DX for self-hosting Nango Auth

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#985]
Nango is still easy to self-hosting for authorization-related purposes: OAuth, API Key auth, proxying, etc. 

But the instructions are out-of-date, as well as the public `docker-compose` and it's not discoverable.

**Comment by t1mmen** [comment]
Ref [this Slack](https://nango-community.slack.com/archives/C04ABR352H0/p1691093312001409), I believe it's no longer possible to seed or set public/secret keys via ENV vars -- they're generated on startup now.

This added some unfortunate friction to our local dev setup (otherwise a 1-click process). We're only using oAuth, fwiw.

If it's possible to do this, I'd love to see it documented as well 🙏 

If this isn't possible, is this a decision you're sticking with? I'd love to change your minds, especially for the "Nango Dev" environment :)

**Comment by bastienbeurier** [comment]
@khaliqgant Does #1050 change anything to the issue @t1mmen raises here? 

This is something that has been asked multiple times to be able to generate Nango Auth environments locally.

**Comment by khaliqgant** [comment]
Yes part of the intention of that PR was to satisfy that specific request.

**Comment by bastienbeurier** [comment]
Amazing! I'll update the docs [here](https://docs.nango.dev/use/self-hosting-instructions) then and ask you for feedback.

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
